services:
  imgcompress:
    image: karimz1/imgcompress:latest
    container_name: imgcompress
    restart: always
    ports:
      - "3001:5000"
    environment:
      - DISABLE_LOGO=false
      - DISABLE_STORAGE_MANAGEMENT=false