services:
  imgcompress:
    image: karimz1/imgcompress:latest
    container_name: imgcompress
    restart: always
    ports:
      - "3001:5000"                     # HOST:CONTAINER â€” change 3001 if needed
    environment:
      - DISABLE_LOGO=true               # Optional: disable mascot
      - DISABLE_STORAGE_MANAGEMENT=true # Optional: disable the Storage Management